# .goreleaser.yaml
builds:
  - main: ./app/
    goos:
      - linux
    goarch:
      - amd64
      - arm64

dockers:
  - image_templates:
      - "docker.io/fdpeiter/random-http-cats:{{ .Version }}"
      - "docker.io/fdpeiter/random-http-cats:latest"
    dockerfile: ./Dockerfile
    goos: linux
    goarch: amd64,arm64
    skip_push: false
    build_flag_templates:
      - --platform=linux/amd64,linux/arm64

# Add your DockerHub credentials to the environment variables
env:
  - DOCKER_USERNAME
  - DOCKER_PASSWORD
